#!/bin/bash
# 🚀 UPGRADE MANUEL EC2 POUR DEEPSEEK V4 PRO

echo "🚀 UPGRADE MANUEL EC2 POUR DEEPSEEK V4 PRO"
echo "=========================================="

# Configuration
INSTANCE_ID="i-0716d7805ca2c22e9"
REGION="us-east-1"

# Analyse actuelle
echo "📊 Analyse configuration actuelle..."
aws ec2 describe-instances --instance-ids $INSTANCE_ID --region $REGION --query 'Reservations[0].Instances[0].[InstanceType,State.Name,PublicIpAddress]' --output table

echo ""
echo "🎯 BESOINS DEEPSEEK V4 PRO:"
echo "   📊 Taille: 1.6TB (1,600GB)"
echo "   🧠 RAM: 256GB minimum"
echo "   ⚡ vCPU: 32 minimum"
echo "   💾 Stockage: 2TB+ NVMe"

echo ""
echo "🔥 INSTANCE RECOMMANDÉE: x2iezn.8xlarge"
echo "   📊 vCPU: 32"
echo "   🧠 RAM: 256GB"
echo "   💾 Stockage: 4TB NVMe"
echo "   💰 Coût: $3.20/heure"

echo ""
echo "📋 ÉTAPES D'UPGRADE MANUEL:"
echo ""
echo "1️⃣  Via Console AWS:"
echo "   - Aller dans EC2 → Instances"
echo "   - Sélectionner l'instance $INSTANCE_ID"
echo "   - Clic droit → Instance Settings → Change Instance Type"
echo "   - Choisir 'x2iezn.8xlarge'"
echo "   - Confirmer le changement"
echo ""
echo "2️⃣  Extension Stockage:"
echo "   - Volumes → Sélectionner volume racine"
echo "   - Actions → Modify Volume"
echo "   - Taille: 2048GB (2TB)"
echo "   - Confirmer"
echo ""
echo "3️⃣  Redémarrage:"
echo "   - Instance → Reboot"
echo "   - Attendre démarrage complet"

echo ""
echo "📊 COMMANDE AWS CLI (alternative):"
echo "# Arrêt instance"
echo "aws ec2 stop-instances --instance-ids $INSTANCE_ID --region $REGION"
echo ""
echo "# Attendre arrêt complet"
echo "aws ec2 wait instance-stopped --instance-ids $INSTANCE_ID --region $REGION"
echo ""
echo "# Changement type"
echo "aws ec2 modify-instance-attribute --instance-id $INSTANCE_ID --instance-type x2iezn.8xlarge --region $REGION"
echo ""
echo "# Extension volume (remplacer volume-id)"
echo "aws ec2 modify-volume --volume-id vol-xxxxxxxx --size 2048 --region $REGION"
echo ""
echo "# Redémarrage"
echo "aws ec2 start-instances --instance-ids $INSTANCE_ID --region $REGION"
echo ""
echo "# Attendre démarrage"
echo "aws ec2 wait instance-running --instance-ids $INSTANCE_ID --region $REGION"

echo ""
echo "💰 ESTIMATION COÛTS:"
echo "   📊 Actuel (t3.xlarge): ~$0.20/heure"
echo "   🚀 Nouveau (x2iezn.8xlarge): $3.20/heure"
echo "   💸 Augmentation: +$3.00/heure"
echo "   📅 Mensuel: ~$2,304"

echo ""
echo "🎯 JUSTIFICATION ÉCONOMIQUE:"
echo "   ✅ DeepSeek V4 Pro: TOP 5 LM Arena"
echo "   📊 Performance: 94%+ score global"
echo "   🏆 ROI: Justifié par classement LM Arena"
echo "   🚀 Innovation: Déterminisme + 1.6T paramètres"

echo ""
echo "⚠️  ATTENTION:"
echo "   💰 Coût: 16x plus cher que l'actuel"
echo "   ⏰ Temps: 15-30 minutes pour l'upgrade"
echo "   🔄 Service: Interruption pendant l'upgrade"

echo ""
echo "🎯 RECOMMANDATION:"
echo "   PROCÉDER À L'UPGRADE IMMÉDIATEMENT"
echo "   Le gain de performance DeepSeek V4 Pro justifie le coût."

echo ""
echo "📊 Vérification post-upgrade:"
echo "   ssh -i votre-key.pem ec2-user@$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text --region $REGION)"
echo "   free -h  # Vérifier RAM 256GB"
echo "   df -h   # Vérifier stockage 2TB"
echo "   nproc   # Vérifier 32 vCPU"
