KNOWLEDGE_BASE = [
    ("lumiere", "est une", "onde electromagnetique", "PHYSIQUE_FOND"),
    ("lumiere", "se deplace a", "300000 km/s dans le vide", "PHYSIQUE_FOND"),
    ("lumiere", "est composee de", "photons", "PHYSIQUE_FOND"),
    ("lumiere", "se reflechit sur", "les surfaces polies", "PHYSIQUE_FOND"),
    ("lumiere", "se refracte dans", "l eau et le verre", "PHYSIQUE_FOND"),
    ("lumiere", "se decompose en", "un spectre de couleurs", "PHYSIQUE_FOND"),
    ("photons", "sont", "les particules de lumiere", "PHYSIQUE_FOND"),
    ("photons", "n ont pas de", "masse", "PHYSIQUE_FOND"),
    ("photons", "transportent", "l energie lumineuse", "PHYSIQUE_FOND"),
    ("onde", "transporte", "energie sans matiere", "PHYSIQUE_FOND"),
    ("onde", "est", "une perturbation qui se propage", "PHYSIQUE_FOND"),
    ("onde", "a une", "frequence et une longueur d onde", "PHYSIQUE_FOND"),
    ("onde", "peut etre", "transversale ou longitudinale", "PHYSIQUE_FOND"),
    ("frequence", "mesure", "le nombre d oscillations par seconde", "PHYSIQUE_FOND"),
    ("frequence", "est", "l inverse de la periode", "PHYSIQUE_FOND"),
    ("frequence", "se mesure en", "Hertz", "PHYSIQUE_FOND"),
    ("resonance", "amplifie", "ondes de meme frequence", "PHYSIQUE_FOND"),
    ("resonance", "est", "le phenomene d amplification par accord de phase", "PHYSIQUE_FOND"),
    ("resonance", "peut detruire", "un pont si la frequence correspond", "PHYSIQUE_FOND"),
    ("interference", "est", "la superposition de deux ondes", "PHYSIQUE_FOND"),
    ("interference", "peut etre", "constructive ou destructive", "PHYSIQUE_FOND"),
    ("diffraction", "est", "la deviation d une onde par un obstacle", "PHYSIQUE_FOND"),
    ("reflexion", "est", "le rebond d une onde sur une surface", "PHYSIQUE_FOND"),
    ("refraction", "est", "le changement de direction d une onde", "PHYSIQUE_FOND"),
    ("energie", "se conserve", "dans un systeme isole", "PHYSIQUE_FOND"),
    ("energie", "existe sous", "plusieurs formes", "PHYSIQUE_FOND"),
    ("energie", "ne peut etre", "ni creee ni detruite", "PHYSIQUE_FOND"),
    ("force", "est", "une action modifiant le mouvement", "PHYSIQUE_FOND"),
    ("force", "se mesure en", "Newtons", "PHYSIQUE_FOND"),
    ("newton", "a decouvert", "les lois du mouvement", "PHYSIQUE_FOND"),
    ("newton", "a formule", "la loi de la gravitation universelle", "PHYSIQUE_FOND"),
    ("gravite", "est", "la courbure de l espace temps", "PHYSIQUE_FOND"),
    ("gravite", "attire", "toute masse vers toute autre masse", "PHYSIQUE_FOND"),
    ("gravite", "est", "la plus faible des forces fondamentales", "PHYSIQUE_FOND"),
    ("einstein", "a decouvert", "la relativite", "PHYSIQUE_FOND"),
    ("einstein", "a formule", "E egal mc deux", "PHYSIQUE_FOND"),
    ("einstein", "a predit", "les ondes gravitationnelles", "PHYSIQUE_FOND"),
    ("relativite", "decrit", "la gravitation comme courbure de l espace", "PHYSIQUE_FOND"),
    ("relativite", "unifie", "espace et temps", "PHYSIQUE_FOND"),
    ("relativite", "predit", "trous noirs et ondes gravitationnelles", "PHYSIQUE_FOND"),
    ("relativite", "a ete verifiee par", "l eclipse de 1919", "PHYSIQUE_FOND"),
    ("maxwell", "a unifie", "electricite et magnetisme", "PHYSIQUE_FOND"),
    ("maxwell", "a predit", "les ondes electromagnetiques", "PHYSIQUE_FOND"),
    ("electromagnetisme", "decrit", "l interaction entre charges electriques", "PHYSIQUE_FOND"),
    ("electromagnetisme", "est", "une des quatre forces fondamentales", "PHYSIQUE_FOND"),
    ("planck", "a introduit", "le quantum d action", "PHYSIQUE_FOND"),
    ("planck", "a decouvert", "la constante de Planck", "PHYSIQUE_FOND"),
    ("bohr", "a propose", "le modele atomique", "PHYSIQUE_FOND"),
    ("schrodinger", "a formule", "l equation d onde", "PHYSIQUE_FOND"),
    ("heisenberg", "a enonce", "le principe d incertitude", "PHYSIQUE_FOND"),
    ("atome", "est compose de", "noyau et electrons", "PHYSIQUE_APPLI"),
    ("atome", "est", "la plus petite unite d un element", "PHYSIQUE_APPLI"),
    ("electron", "orbite", "autour du noyau", "PHYSIQUE_APPLI"),
    ("electron", "est", "une particule elementaire", "PHYSIQUE_APPLI"),
    ("electron", "a une charge", "negative", "PHYSIQUE_APPLI"),
    ("proton", "est", "une particule du noyau atomique", "PHYSIQUE_APPLI"),
    ("proton", "a une charge", "positive", "PHYSIQUE_APPLI"),
    ("neutron", "est", "une particule du noyau sans charge", "PHYSIQUE_APPLI"),
    ("noyau", "contient", "protons et neutrons", "PHYSIQUE_APPLI"),
    ("noyau", "est", "tres dense", "PHYSIQUE_APPLI"),
    ("quark", "est", "un constituant elementaire des protons", "PHYSIQUE_APPLI"),
    ("quark", "existe en", "six saveurs differentes", "PHYSIQUE_APPLI"),
    ("molecule", "est", "un assemblage d atomes", "PHYSIQUE_APPLI"),
    ("molecule", "est liee par", "des liaisons chimiques", "PHYSIQUE_APPLI"),
    ("isotope", "est", "un atome avec un nombre different de neutrons", "PHYSIQUE_APPLI"),
    ("radioactivite", "est", "la desintegration de noyaux instables", "PHYSIQUE_APPLI"),
    ("curie", "a decouvert", "la radioactivite", "PHYSIQUE_APPLI"),
    ("curie", "a isole", "le radium et le polonium", "PHYSIQUE_APPLI"),
    ("fission", "est", "la division d un noyau lourd", "PHYSIQUE_APPLI"),
    ("fusion", "est", "la combinaison de noyaux legers", "PHYSIQUE_APPLI"),
    ("fusion", "alimente", "le soleil et les etoiles", "PHYSIQUE_APPLI"),
    ("laser", "produit", "lumiere coherente", "PHYSIQUE_APPLI"),
    ("laser", "est utilise pour", "la chirurgie et les telecommunications", "PHYSIQUE_APPLI"),
    ("aimant", "cree", "un champ magnetique", "PHYSIQUE_APPLI"),
    ("aimant", "a deux poles", "nord et sud", "PHYSIQUE_APPLI"),
    ("batterie", "stocke", "energie chimique", "PHYSIQUE_APPLI"),
    ("batterie", "produit", "courant electrique", "PHYSIQUE_APPLI"),
    ("moteur", "transforme", "energie en mouvement", "PHYSIQUE_APPLI"),
    ("generateur", "transforme", "mouvement en electricite", "PHYSIQUE_APPLI"),
    ("internet", "connecte", "les ordinateurs du monde", "PHYSIQUE_APPLI"),
    ("internet", "utilise", "le protocole TCP IP", "PHYSIQUE_APPLI"),
    ("ordinateur", "traite", "information binaire", "PHYSIQUE_APPLI"),
    ("ordinateur", "est compose de", "processeur et memoire", "PHYSIQUE_APPLI"),
    ("transistor", "est", "le composant de base des circuits", "PHYSIQUE_APPLI"),
    ("transistor", "amplifie ou bloque", "le courant electrique", "PHYSIQUE_APPLI"),
    ("supraconducteur", "conduit", "electricite sans resistance", "PHYSIQUE_APPLI"),
    ("supraconducteur", "necessite", "de tres basses temperatures", "PHYSIQUE_APPLI"),
    ("laser", "signifie", "amplification de lumiere par emission stimulee", "PHYSIQUE_APPLI"),
    ("hologramme", "est", "une image tridimensionnelle par interference", "PHYSIQUE_APPLI"),
    ("hologramme", "utilise", "la lumiere laser", "PHYSIQUE_APPLI"),
    ("fibre optique", "transmet", "la lumiere sur de longues distances", "PHYSIQUE_APPLI"),
    ("fibre optique", "utilise", "la reflexion totale interne", "PHYSIQUE_APPLI"),
    ("radar", "detecte", "les objets par reflexion d ondes", "PHYSIQUE_APPLI"),
    ("radar", "utilise", "des ondes radio", "PHYSIQUE_APPLI"),
    ("sonar", "detecte", "les objets sous l eau par ondes sonores", "PHYSIQUE_APPLI"),
    ("ecran", "affiche", "des images par pixels lumineux", "PHYSIQUE_APPLI"),
    ("carte graphique", "calcule", "les images pour l affichage", "PHYSIQUE_APPLI"),
    ("phi", "est le", "nombre d or", "MATHS_PURES"),
    ("phi", "vaut", "1.618 environ", "MATHS_PURES"),
    ("phi", "est", "la proportion divine", "MATHS_PURES"),
    ("phi", "apparait dans", "la suite de Fibonacci", "MATHS_PURES"),
    ("phi", "est", "le nombre le plus irrationnel", "MATHS_PURES"),
    ("pi", "est le", "rapport cercle diametre", "MATHS_PURES"),
    ("pi", "vaut", "3.14159 environ", "MATHS_PURES"),
    ("pi", "est", "un nombre transcendant", "MATHS_PURES"),
    ("e", "est", "la base du logarithme naturel", "MATHS_PURES"),
    ("e", "vaut", "2.718 environ", "MATHS_PURES"),
    ("e", "est", "la limite de un plus un sur n puissance n", "MATHS_PURES"),
    ("zero", "represente", "le neant", "MATHS_PURES"),
    ("zero", "est", "l element neutre de l addition", "MATHS_PURES"),
    ("zero", "a ete invente par", "les mathematiciens indiens", "MATHS_PURES"),
    ("infini", "represente", "l illimite", "MATHS_PURES"),
    ("infini", "est", "ce qui n a pas de fin", "MATHS_PURES"),
    ("infini", "existe en", "plusieurs tailles selon Cantor", "MATHS_PURES"),
    ("nombre", "est", "une abstraction representant une quantite", "MATHS_PURES"),
    ("nombre premier", "est", "divisible seulement par un et lui meme", "MATHS_PURES"),
    ("nombre premier", "est", "infini selon Euclide", "MATHS_PURES"),
    ("nombre complexe", "a", "une partie reelle et une partie imaginaire", "MATHS_PURES"),
    ("i", "est", "la racine carree de moins un", "MATHS_PURES"),
    ("addition", "est", "l operation fondamentale", "MATHS_PURES"),
    ("soustraction", "est", "l inverse de l addition", "MATHS_PURES"),
    ("multiplication", "est", "l addition repetee", "MATHS_PURES"),
    ("division", "est", "l inverse de la multiplication", "MATHS_PURES"),
    ("fraction", "represente", "une partie d un tout", "MATHS_PURES"),
    ("geometrie", "etudie", "les formes et l espace", "MATHS_PURES"),
    ("geometrie", "est", "la mesure de la terre", "MATHS_PURES"),
    ("triangle", "a", "trois cotes et trois angles", "MATHS_PURES"),
    ("triangle", "a une somme d angles de", "180 degres", "MATHS_PURES"),
    ("cercle", "est", "l ensemble des points equidistants d un centre", "MATHS_PURES"),
    ("sphere", "est", "l ensemble des points equidistants dans l espace", "MATHS_PURES"),
    ("polygone", "est", "une figure fermee a plusieurs cotes", "MATHS_PURES"),
    ("fractale", "est", "une forme autorepetee a toutes les echelles", "MATHS_PURES"),
    ("fractale", "a une", "dimension non entiere", "MATHS_PURES"),
    ("fractale", "decrit", "les cotes, les choux et les nuages", "MATHS_PURES"),
    ("logique", "est", "l art du raisonnement juste", "MATHS_PURES"),
    ("logique", "repose sur", "le principe de non contradiction", "MATHS_PURES"),
    ("logique", "utilise", "des propositions et des connecteurs", "MATHS_PURES"),
    ("theoreme", "est", "une proposition demontrable", "MATHS_PURES"),
    ("axiome", "est", "une proposition admise sans demonstration", "MATHS_PURES"),
    ("godel", "a demontre", "l incompletude des mathematiques", "MATHS_PURES"),
    ("equation", "exprime", "l egalite entre deux expressions", "MATHS_PURES"),
    ("equation", "a une", "ou plusieurs inconnues", "MATHS_PURES"),
    ("algebre", "utilise", "des lettres pour representer des nombres", "MATHS_PURES"),
    ("algebre", "a ete developpee par", "Al Khwarizmi", "MATHS_PURES"),
    ("trigonometrie", "etudie", "les relations entre angles et longueurs", "MATHS_PURES"),
    ("sinus", "est le rapport", "cote oppose sur hypotenuse", "MATHS_PURES"),
    ("cosinus", "est le rapport", "cote adjacent sur hypotenuse", "MATHS_PURES"),
]
