# Auto-generated from ka_care_features.json
# Merge into ka_care.py SYMPTOM_FEATURES

# Features étendues pour maladies tropicales
EXTRA_FEATURES = {
    "abattement": {"general": 0.8, "psychologique": 0.8},
    "amaigrissement": {"general": 0.8, "digestif": 0.8},
    "ataxie": {"neurologique": 0.8, "general": 0.8},
    "bradycardie": {"cardiaque": 0.8, "general": 0.8},
    "bradycardie_relative": {"cardiaque": 0.8, "general": 0.8},
    "chancre_inoculation": {"cutane": 0.8, "general": 0.8, "trypano_specifique": 0.8},
    "choc_hypovolémique": {"cardiaque": 0.8, "general": 0.8, "urgence": 0.8},
    "conjonctivite": {"ORL": 0.8, "cutane": 0.8, "zika_specifique": 0.8},
    "crampes_musculaires": {"musculaire": 0.8, "douleur": 0.8, "general": 0.8},
    "cécité_progressive": {"neurologique": 0.8, "tete": 0.8, "onchocercose_specifique": 0.8},
    "diarrhée_aqueuse_profuse": {"digestif": 0.8, "general": 0.8, "cholera_specifique": 0.8},
    "diarrhée_sanglante": {"digestif": 0.8, "general": 0.8},
    "douleurs_rétro_orbitaires": {"tete": 0.8, "douleur": 0.8, "neurologique": 0.8, "dengue_specifique": 0.8},
    "dépigmentation": {"cutane": 0.8, "general": 0.8},
    "déshydratation_sévère": {"general": 0.8, "digestif": 0.8, "urgence_hydrique": 0.8},
    "hydrocèle": {"urinaire": 0.8, "general": 0.8, "filariose_specifique": 0.8},
    "hématurie": {"urinaire": 0.8, "general": 0.8, "bilharziose_specifique": 0.8},
    "hémorragies": {"cutane": 0.8, "general": 0.8, "urgence_hemorragique": 0.8},
    "hépatomégalie": {"digestif": 0.8, "general": 0.8},
    "ictère": {"digestif": 0.8, "general": 0.8, "fievre_jaune_specifique": 0.8},
    "insuffisance_rénale": {"urinaire": 0.8, "general": 0.8, "renale": 0.8},
    "lymphangite": {"cutane": 0.8, "general": 0.8},
    "lymphœdème": {"cutane": 0.8, "general": 0.8, "filariose_specifique": 0.8},
    "léthargie": {"neurologique": 0.8, "general": 0.8, "psychologique": 0.8},
    "myalgies_mollets": {"musculaire": 0.8, "douleur": 0.8, "leptospirose_specifique": 0.8},
    "nodules_sous_cutanés": {"cutane": 0.8, "general": 0.8, "onchocercose_specifique": 0.8},
    "oligurie": {"urinaire": 0.8, "general": 0.8, "renale": 0.8},
    "pancytopénie": {"general": 0.8, "hematologique": 0.8},
    "pli_cutané": {"cutane": 0.8, "general": 0.8},
    "polyarthralgie": {"articulaire": 0.8, "douleur": 0.8, "chikungunya_specifique": 0.8},
    "prurit": {"cutane": 0.8, "general": 0.8},
    "prurit_intense": {"cutane": 0.8, "general": 0.8, "onchocercose_specifique": 0.8},
    "saignements_muqueuses": {"cutane": 0.8, "general": 0.8, "urgence_hemorragique": 0.8},
    "splénomégalie_massive": {"general": 0.8, "leishmaniose_specifique": 0.8},
    "taches_roses": {"cutane": 0.8, "general": 0.8},
    "troubles_sommeil": {"neurologique": 0.8, "psychologique": 0.8, "trypano_specifique": 0.8},
    "yeux_enfoncés": {"general": 0.8, "tete": 0.8},
    "éléphantiasis": {"cutane": 0.8, "general": 0.8, "filariose_specifique": 0.8},
}