"""
🌊 Wave Emit — Conversion du langage harmonique vers les langages classiques
==============================================================================

Le langage harmonique est un IR (intermediate representation). Comme tout IR,
il peut être CONVERTI vers plusieurs backends :

    emit_python(program)      → Python exécutable
    emit_javascript(program)  → JavaScript
    emit_typescript(program)  → TypeScript
    emit(program, target)     → dispatch générique

Chaque conversion est déterministe et testable : le même AST produit le même
code. Les nœuds ondulatoires (Encode, Bind, Resonance...) sont émis comme des
appels à wave_lang (Python) ou comme des commentaires documentés (JS — le
bridge API existe côté serveur). Les nœuds computationnels (MathOp,
FunctionCall, CodeBlock, IfStmt, WhileStmt) sont émis en code classique natif.

Usage :
    from wave_emit import emit_python, emit_javascript, emit

    ast = parse("x = ADD(2, MUL(3, 4)) ; RETURN x")
    print(emit_python(ast))   # x = (2 + (3 * 4)) ; return x
    print(emit_javascript(ast))  # const x = (2 + (3 * 4)); return x;
"""

from __future__ import annotations

import math
from typing import List, Dict, Optional, Union

from wave_ir import (Program, Assign, Store, Query, Return,
                     CodeBlock, IfStmt, WhileStmt, FunctionDef, ForStmt,
                     AugAssign,
                     Encode, Decode, Bind, Unbind, Superpose,
                     Resonance, Rotate, Normalize, Interfere,
                     Diffract, FilterLP, FilterHP, FilterBP,
                     PhaseShift, Emerge, Oppose, Amplify, BindMany,
                     Var, Literal, StringLit, MathOp, FunctionCall,
                     ListLiteral, Subscript, TernaryExpr, LambdaExpr,
                     RawCode)


# ═══════════════════════════════════════════════════════════════════════════════
# TABLE DES OPÉRATIONS MATHÉMATIQUES PAR BACKEND
# ═══════════════════════════════════════════════════════════════════════════════

# Opérations binaires : op(a, b) → code
_BINARY_OPS_PY = {
    'ADD': lambda a, b: f"({a} + {b})",
    'SUB': lambda a, b: f"({a} - {b})",
    'MUL': lambda a, b: f"({a} * {b})",
    'DIV': lambda a, b: f"({a} / {b})",
    'POW': lambda a, b: f"({a} ** {b})",
    'MOD': lambda a, b: f"({a} % {b})",
    # Comparaisons
    'GT': lambda a, b: f"({a} > {b})",
    'GE': lambda a, b: f"({a} >= {b})",
    'LT': lambda a, b: f"({a} < {b})",
    'LE': lambda a, b: f"({a} <= {b})",
    'EQ': lambda a, b: f"({a} == {b})",
    'NE': lambda a, b: f"({a} != {b})",
}

_BINARY_OPS_JS = {
    'ADD': lambda a, b: f"({a} + {b})",
    'SUB': lambda a, b: f"({a} - {b})",
    'MUL': lambda a, b: f"({a} * {b})",
    'DIV': lambda a, b: f"({a} / {b})",
    'POW': lambda a, b: f"Math.pow({a}, {b})",
    'MOD': lambda a, b: f"({a} % {b})",
    'GT': lambda a, b: f"({a} > {b})",
    'GE': lambda a, b: f"({a} >= {b})",
    'LT': lambda a, b: f"({a} < {b})",
    'LE': lambda a, b: f"({a} <= {b})",
    'EQ': lambda a, b: f"({a} === {b})",
    'NE': lambda a, b: f"({a} !== {b})",
}

# Opérations unaires : op(a) → code
_UNARY_OPS_PY = {
    'SQRT': lambda a: f"math.sqrt({a})",
    'NEG': lambda a: f"(-{a})",
    'ABS': lambda a: f"abs({a})",
    'FLOOR': lambda a: f"math.floor({a})",
}

_UNARY_OPS_JS = {
    'SQRT': lambda a: f"Math.sqrt({a})",
    'NEG': lambda a: f"(-{a})",
    'ABS': lambda a: f"Math.abs({a})",
    'FLOOR': lambda a: f"Math.floor({a})",
}


# ═══════════════════════════════════════════════════════════════════════════════
# BACKEND PYTHON
# ═══════════════════════════════════════════════════════════════════════════════

def emit_python(program: Program, include_wave_lang: bool = True,
                include_holograms: bool = True) -> str:
    """
    Convertit un programme harmonique en Python exécutable.

    Args:
        program: AST wave_ir
        include_wave_lang: ajouter les imports wave_lang (pour les nœuds ondes)
        include_holograms: initialiser les HolographicMemory nécessaires

    Returns:
        code Python
    """
    lines: List[str] = []

    # Toujours nécessaire (MathOp SQRT/FLOOR/ABS...)
    lines += ["# Generated by Wave Emit — Langage harmonique → Python", "", "import math"]

    if include_wave_lang:
        lines += [
            "",
            "from wave_lang import (",
            "    encode, decode, bind, unbind, superpose,",
            "    resonate, coherence, rotate, normalize,",
            "    interfere, diffract, filter_wave, phase_shift,",
            "    emerge, oppose, amplify, bind_many,",
            "    HolographicMemory, abc_kernel,",
            ")",
            "",
        ]

    # Initialiser la mémoire holographique si nécessaire
    if include_holograms:
        has_store_or_query = any(
            isinstance(s, (Store, Query)) for s in program.statements)
        if has_store_or_query:
            holograms = set()
            for s in program.statements:
                if isinstance(s, (Store, Query)):
                    holograms.add(s.hologram)
            for h in holograms:
                lines.append(f"{h} = HolographicMemory()")
            lines.append("")

    for stmt in program.statements:
        py = _stmt_py(stmt, indent=0)
        if py:
            lines.append(py)

    return "\n".join(lines)


def _stmt_py(stmt, indent: int = 0) -> str:
    """Convertit un statement en Python."""
    pad = "    " * indent
    if isinstance(stmt, Assign):
        return f"{pad}{stmt.name} = {_expr_py(stmt.value)}"
    elif isinstance(stmt, Store):
        return f"{pad}{stmt.hologram}.store_raw({_expr_py(stmt.value)})"
    elif isinstance(stmt, Query):
        return f"{pad}{stmt.name} = {stmt.hologram}.query({_expr_py(stmt.value)})"
    elif isinstance(stmt, Return):
        return f"{pad}return {_expr_py(stmt.value)}"
    elif isinstance(stmt, CodeBlock):
        body = "\n".join(_stmt_py(s, indent) for s in stmt.body)
        return body
    elif isinstance(stmt, IfStmt):
        lines = [f"{pad}if {_expr_py(stmt.condition)}:"]
        for s in stmt.then_body:
            lines.append(_stmt_py(s, indent + 1))
        if stmt.else_body is not None and stmt.else_body:
            lines.append(f"{pad}else:")
            for s in stmt.else_body:
                lines.append(_stmt_py(s, indent + 1))
        return "\n".join(lines)
    elif isinstance(stmt, WhileStmt):
        lines = [f"{pad}while {_expr_py(stmt.condition)}:"]
        for s in stmt.body:
            lines.append(_stmt_py(s, indent + 1))
        return "\n".join(lines)
    elif isinstance(stmt, FunctionDef):
        params = ", ".join(stmt.params)
        lines = [f"{pad}def {stmt.name}({params}):"]
        if not stmt.body:
            lines.append(f"{pad}    pass")
        for s in stmt.body:
            lines.append(_stmt_py(s, indent + 1))
        return "\n".join(lines)
    elif isinstance(stmt, ForStmt):
        lines = [f"{pad}for {stmt.target} in {_expr_py(stmt.iterable)}:"]
        if not stmt.body:
            lines.append(f"{pad}    pass")
        for s in stmt.body:
            lines.append(_stmt_py(s, indent + 1))
        return "\n".join(lines)
    elif isinstance(stmt, AugAssign):
        op_map = {'ADD': '+=', 'SUB': '-=', 'MUL': '*=', 'DIV': '/='}
        sym = op_map.get(stmt.op, stmt.op)
        return f"{pad}{stmt.name} {sym} {_expr_py(stmt.value)}"
    return ""


def _expr_py(expr) -> str:
    """Convertit une expression en Python."""
    if isinstance(expr, Var):
        return expr.name
    elif isinstance(expr, Literal):
        v = expr.value
        return repr(int(v)) if isinstance(v, float) and v.is_integer() else repr(v)
    elif isinstance(expr, StringLit):
        return repr(expr.value)
    elif isinstance(expr, MathOp):
        if expr.right is not None and expr.op in _BINARY_OPS_PY:
            return _BINARY_OPS_PY[expr.op](_expr_py(expr.left),
                                           _expr_py(expr.right))
        if expr.op in _UNARY_OPS_PY:
            return _UNARY_OPS_PY[expr.op](_expr_py(expr.left))
        # Fallback : appel fonction
        args = [_expr_py(expr.left)]
        if expr.right is not None:
            args.append(_expr_py(expr.right))
        return f"{expr.op.lower()}({', '.join(args)})"
    elif isinstance(expr, FunctionCall):
        args = ", ".join(_expr_py(a) for a in expr.args)
        return f"{expr.name}({args})"
    # Nœuds ondulatoires → appels wave_lang
    elif isinstance(expr, Encode):
        return f'encode("{expr.text}")'
    elif isinstance(expr, Decode):
        return f"decode({_expr_py(expr.psi)}, top_k={expr.top_k})"
    elif isinstance(expr, Bind):
        return f"bind({_expr_py(expr.left)}, {_expr_py(expr.right)})"
    elif isinstance(expr, Unbind):
        return f"unbind({_expr_py(expr.left)}, {_expr_py(expr.right)})"
    elif isinstance(expr, Superpose):
        args = ", ".join(_expr_py(p) for p in expr.psis)
        return f"superpose({args})"
    elif isinstance(expr, Resonance):
        return f"resonate({_expr_py(expr.left)}, {_expr_py(expr.right)})"
    elif isinstance(expr, Rotate):
        return f"rotate({_expr_py(expr.psi)}, {expr.angle})"
    elif isinstance(expr, Normalize):
        return f"normalize({_expr_py(expr.psi)})"
    elif isinstance(expr, Interfere):
        return (f"interfere({_expr_py(expr.base)}, {_expr_py(expr.other)}, "
                f"epsilon={expr.epsilon})")
    elif isinstance(expr, Diffract):
        inv = ", inverse=True" if expr.inverse else ""
        return f"diffract({_expr_py(expr.psi)}{inv})"
    elif isinstance(expr, FilterLP):
        return f"filter_wave({_expr_py(expr.psi)}, low_pass={expr.cutoff:.0f})"
    elif isinstance(expr, FilterHP):
        return f"filter_wave({_expr_py(expr.psi)}, high_pass={expr.cutoff:.0f})"
    elif isinstance(expr, FilterBP):
        return (f"filter_wave({_expr_py(expr.psi)}, "
                f"band_pass=({expr.low:.0f}, {expr.high:.0f}))")
    elif isinstance(expr, PhaseShift):
        return f"phase_shift({_expr_py(expr.psi)}, {expr.shift})"
    elif isinstance(expr, Emerge):
        args = ", ".join(_expr_py(p) for p in expr.psis)
        return f"emerge({args}, temperature={expr.temperature})"
    elif isinstance(expr, Oppose):
        return f"oppose({_expr_py(expr.left)}, {_expr_py(expr.right)})"
    elif isinstance(expr, Amplify):
        return (f"amplify({_expr_py(expr.psi)}, {_expr_py(expr.component)}, "
                f"boost={expr.boost})")
    elif isinstance(expr, BindMany):
        args = ", ".join(_expr_py(p) for p in expr.psis)
        return f"bind_many({args})"
    elif isinstance(expr, ListLiteral):
        items = ", ".join(_expr_py(i) for i in expr.items)
        return f"[{items}]"
    elif isinstance(expr, Subscript):
        return f"{_expr_py(expr.obj)}[{_expr_py(expr.index)}]"
    elif isinstance(expr, TernaryExpr):
        return (f"({_expr_py(expr.if_true)} if "
                f"{_expr_py(expr.condition)} else {_expr_py(expr.if_false)})")
    elif isinstance(expr, LambdaExpr):
        params = ", ".join(expr.params)
        return f"lambda {params}: {_expr_py(expr.body)}"
    elif isinstance(expr, RawCode):
        return expr.text
    return f"# <? {type(expr).__name__} ?>"


# ═══════════════════════════════════════════════════════════════════════════════
# BACKEND JAVASCRIPT
# ═══════════════════════════════════════════════════════════════════════════════

def emit_javascript(program: Program) -> str:
    """
    Convertit un programme harmonique en JavaScript.

    Les nœuds ondulatoires sont émis en commentaires documentés
    (le bridge wave_lang est côté serveur) ; les nœuds computationnels
    sont émis en JS natif.
    """
    lines = [
        "// Generated by Wave Emit — Langage harmonique → JavaScript",
        "",
    ]
    defined: set = set()
    for stmt in program.statements:
        js = _stmt_js(stmt, indent=0, defined=defined)
        if js:
            lines.append(js)
    return "\n".join(lines)


def _stmt_js(stmt, indent: int = 0, defined: Optional[set] = None) -> str:
    """Convertit un statement en JavaScript."""
    if defined is None:
        defined = set()
    pad = "    " * indent
    if isinstance(stmt, Assign):
        # 'let' uniquement à la première définition (pas de re-déclaration)
        if stmt.name in defined:
            return f"{pad}{stmt.name} = {_expr_js(stmt.value)};"
        defined.add(stmt.name)
        return f"{pad}let {stmt.name} = {_expr_js(stmt.value)};"
    elif isinstance(stmt, Store):
        return (f"{pad}// HolographicMemory store: {stmt.hologram}"
                f".store_raw({_expr_js(stmt.value)})")
    elif isinstance(stmt, Query):
        return (f"{pad}// HolographicMemory query: {stmt.name} = "
                f"{stmt.hologram}.query({_expr_js(stmt.value)})")
    elif isinstance(stmt, Return):
        return f"{pad}return {_expr_js(stmt.value)};"
    elif isinstance(stmt, CodeBlock):
        return "\n".join(_stmt_js(s, indent, defined) for s in stmt.body)
    elif isinstance(stmt, IfStmt):
        lines = [f"{pad}if ({_expr_js(stmt.condition)}) {{"]
        for s in stmt.then_body:
            lines.append(_stmt_js(s, indent + 1, defined))
        if stmt.else_body is not None and stmt.else_body:
            lines.append(f"{pad}}} else {{")
            for s in stmt.else_body:
                lines.append(_stmt_js(s, indent + 1, defined))
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    elif isinstance(stmt, WhileStmt):
        lines = [f"{pad}while ({_expr_js(stmt.condition)}) {{"]
        for s in stmt.body:
            lines.append(_stmt_js(s, indent + 1, defined))
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    elif isinstance(stmt, FunctionDef):
        params = ", ".join(stmt.params)
        lines = [f"{pad}function {stmt.name}({params}) {{"]
        # Les paramètres sont déjà déclarés (pas de 'let' dans le corps)
        for p in stmt.params:
            defined.add(p)
        for s in stmt.body:
            lines.append(_stmt_js(s, indent + 1, defined))
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    elif isinstance(stmt, ForStmt):
        lines = [f"{pad}for (const {stmt.target} of {_expr_js(stmt.iterable)}) {{"]
        for s in stmt.body:
            lines.append(_stmt_js(s, indent + 1, defined))
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    elif isinstance(stmt, AugAssign):
        op_map = {'ADD': '+=', 'SUB': '-=', 'MUL': '*=', 'DIV': '/='}
        sym = op_map.get(stmt.op, stmt.op)
        return f"{pad}{stmt.name} {sym} {_expr_js(stmt.value)};"
    return ""


def _expr_js(expr) -> str:
    """Convertit une expression en JavaScript."""
    if isinstance(expr, Var):
        return expr.name
    elif isinstance(expr, Literal):
        v = expr.value
        return repr(int(v)) if isinstance(v, float) and v.is_integer() else repr(v)
    elif isinstance(expr, StringLit):
        return repr(expr.value)
    elif isinstance(expr, MathOp):
        if expr.right is not None and expr.op in _BINARY_OPS_JS:
            return _BINARY_OPS_JS[expr.op](_expr_js(expr.left),
                                           _expr_js(expr.right))
        if expr.op in _UNARY_OPS_JS:
            return _UNARY_OPS_JS[expr.op](_expr_js(expr.left))
        args = [_expr_js(expr.left)]
        if expr.right is not None:
            args.append(_expr_js(expr.right))
        return f"{expr.op.lower()}({', '.join(args)})"
    elif isinstance(expr, FunctionCall):
        args = ", ".join(_expr_js(a) for a in expr.args)
        return f"{expr.name}({args})"
    # Nœuds ondulatoires → commentaires documentés
    elif isinstance(expr, Encode):
        return f"/* ψ = encode('{expr.text}') */ null"
    elif isinstance(expr, Decode):
        return f"/* decode(ψ) */ null"
    elif isinstance(expr, (Bind, Unbind, Superpose, Resonance, Emerge,
                           Oppose, Amplify, BindMany, Normalize, Rotate,
                           Interfere, Diffract, FilterLP, FilterHP, FilterBP,
                           PhaseShift)):
        return f"/* {type(expr).__name__} (wave_lang, serveur) */ null"
    elif isinstance(expr, ListLiteral):
        items = ", ".join(_expr_js(i) for i in expr.items)
        return f"[{items}]"
    elif isinstance(expr, Subscript):
        return f"{_expr_js(expr.obj)}[{_expr_js(expr.index)}]"
    elif isinstance(expr, TernaryExpr):
        return (f"({_expr_js(expr.condition)} ? {_expr_js(expr.if_true)} "
                f": {_expr_js(expr.if_false)})")
    elif isinstance(expr, LambdaExpr):
        params = ", ".join(expr.params)
        return f"({params}) => {_expr_js(expr.body)}"
    elif isinstance(expr, RawCode):
        return expr.text
    return f"/* <? {type(expr).__name__} ?> */ null"


# ═══════════════════════════════════════════════════════════════════════════════
# BACKEND TYPESCRIPT + DISPATCH
# ═══════════════════════════════════════════════════════════════════════════════

def emit_typescript(program: Program) -> str:
    """
    Convertit un programme harmonique en TypeScript.

    Même structure que JavaScript, avec des types annotés sur les Assign
    (nombre si le RHS est un MathOp, chaîne si StringLit, sinon any).
    """
    lines = [
        "// Generated by Wave Emit — Langage harmonique → TypeScript",
        "",
    ]
    defined: set = set()
    for stmt in program.statements:
        ts = _stmt_ts(stmt, indent=0, defined=defined)
        if ts:
            lines.append(ts)
    return "\n".join(lines)


def _ts_type(expr) -> str:
    """Infère le type TypeScript d'une expression."""
    if isinstance(expr, MathOp):
        return "number"
    if isinstance(expr, Literal):
        return "number"
    if isinstance(expr, StringLit):
        return "string"
    if isinstance(expr, FunctionCall):
        return "any"
    return "any"


def _stmt_ts(stmt, indent: int = 0, defined: Optional[set] = None) -> str:
    """Convertit un statement en TypeScript."""
    if defined is None:
        defined = set()
    pad = "    " * indent
    if isinstance(stmt, Assign):
        if stmt.name in defined:
            return f"{pad}{stmt.name} = {_expr_js(stmt.value)};"
        defined.add(stmt.name)
        return (f"{pad}let {stmt.name}: {_ts_type(stmt.value)} = "
                f"{_expr_js(stmt.value)};")
    if isinstance(stmt, Return):
        return f"{pad}return {_expr_js(stmt.value)};"
    if isinstance(stmt, CodeBlock):
        return "\n".join(_stmt_ts(s, indent, defined) for s in stmt.body)
    if isinstance(stmt, IfStmt):
        lines = [f"{pad}if ({_expr_js(stmt.condition)}) {{"]
        for s in stmt.then_body:
            lines.append(_stmt_ts(s, indent + 1, defined))
        if stmt.else_body is not None and stmt.else_body:
            lines.append(f"{pad}}} else {{")
            for s in stmt.else_body:
                lines.append(_stmt_ts(s, indent + 1, defined))
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    if isinstance(stmt, WhileStmt):
        lines = [f"{pad}while ({_expr_js(stmt.condition)}) {{"]
        for s in stmt.body:
            lines.append(_stmt_ts(s, indent + 1, defined))
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    if isinstance(stmt, FunctionDef):
        params = ", ".join(stmt.params)
        lines = [f"{pad}function {stmt.name}({params}): any {{"]
        for p in stmt.params:
            defined.add(p)
        for s in stmt.body:
            lines.append(_stmt_ts(s, indent + 1, defined))
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    if isinstance(stmt, ForStmt):
        lines = [f"{pad}for (const {stmt.target} of {_expr_js(stmt.iterable)}) {{"]
        for s in stmt.body:
            lines.append(_stmt_ts(s, indent + 1, defined))
        lines.append(f"{pad}}}")
        return "\n".join(lines)
    if isinstance(stmt, AugAssign):
        op_map = {'ADD': '+=', 'SUB': '-=', 'MUL': '*=', 'DIV': '/='}
        sym = op_map.get(stmt.op, stmt.op)
        return f"{pad}{stmt.name} {sym} {_expr_js(stmt.value)};"
    # Store/Query → commentaires (bridge serveur)
    if isinstance(stmt, Store):
        return f"{pad}// store: {stmt.hologram}.store_raw(...)"
    if isinstance(stmt, Query):
        return f"{pad}// query: {stmt.name} = {stmt.hologram}.query(...)"
    return ""


def emit(program: Program, target: str = 'python') -> str:
    """
    Dispatch générique : convertit vers la cible demandée.

    Args:
        program: AST wave_ir
        target: 'python', 'javascript', 'typescript' (ou alias 'js', 'ts')

    Returns:
        code source de la cible
    """
    target = target.lower()
    if target in ('python', 'py'):
        return emit_python(program)
    if target in ('javascript', 'js'):
        return emit_javascript(program)
    if target in ('typescript', 'ts'):
        return emit_typescript(program)
    raise ValueError(f"Cible inconnue: {target} (python, javascript, typescript)")


# ═══════════════════════════════════════════════════════════════════════════════
# SELF-TEST
# ═══════════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    print("=" * 65)
    print("  🌊 WAVE EMIT — Conversion multi-backend")
    print("=" * 65)

    from wave_ir import parse

    src = """
x = ADD(2, MUL(3, 4))
y = SQRT(16)
IF(x > 10) { z = SUB(x, 10) ; RETURN z } ELSE { RETURN y }
WHILE(x < 100) { x = ADD(x, 1) }
"""
    ast = parse(src)

    print("\n── SOURCE HARMONIQUE ──")
    print(ast.to_wave())

    print("\n── PYTHON ──")
    print(emit_python(ast))

    print("\n── JAVASCRIPT ──")
    print(emit_javascript(ast))

    print("\n── TYPESCRIPT ──")
    print(emit_typescript(ast))

    # Vérification : le code Python généré s'exécute et calcule
    print("\n── EXÉCUTION DU CODE PYTHON GÉNÉRÉ ──")
    prog = parse("x = ADD(2, MUL(3, 4)) ; RETURN x")
    py = emit_python(prog, include_wave_lang=False, include_holograms=False)
    # Le RETURN est au niveau module → envelopper dans une fonction
    wrapped = "def _main():\n    " + py.replace("\n", "\n    ") + "\nresult = _main()"
    ns: Dict = {}
    exec(wrapped, ns)
    print(f"  result = {ns.get('result')} (attendu: 14)")
    print("  " + py.replace('\n', '\n  '))

    print("\n" + "=" * 65)
    print("  ✅ Wave Emit — Conversion fonctionnelle.")
    print("=" * 65)
