"""
ALPHAFOLD — Entrée/Sortie PDB et Métriques
============================================
Parser et writer PDB, parsing FASTA, métriques de comparaison
structurale (RMSD, TM-score, GDT-TS).

Author: Univers-Holistique
"""

import math
import numpy as np
from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass

from .amino_acids import get_amino_acid, parse_sequence
from .backbone import ProteinStructure, ResidueAtoms, HarmonicBackbone, rmsd

# ═══════════════════════════════════════════════════════════════════════════════
# PDB PARSER
# ═══════════════════════════════════════════════════════════════════════════════

# Mapping PDB atom names → residue atom names
PDB_BACKBONE_ATOMS = {'N', 'CA', 'C', 'O'}

# Codes 3 lettres → 1 lettre
AA3TO1 = {
    'ALA': 'A', 'ARG': 'R', 'ASN': 'N', 'ASP': 'D', 'CYS': 'C',
    'GLN': 'Q', 'GLU': 'E', 'GLY': 'G', 'HIS': 'H', 'ILE': 'I',
    'LEU': 'L', 'LYS': 'K', 'MET': 'M', 'PHE': 'F', 'PRO': 'P',
    'SER': 'S', 'THR': 'T', 'TRP': 'W', 'TYR': 'Y', 'VAL': 'V',
}

AA1TO3 = {v: k for k, v in AA3TO1.items()}


def parse_pdb(filepath: str) -> ProteinStructure:
    """
    Parse un fichier PDB et extrait les atomes du backbone.

    Args:
        filepath: chemin vers le fichier PDB

    Returns:
        ProteinStructure avec les coordonnées des atomes
    """
    with open(filepath, 'r') as f:
        lines = f.readlines()

    # Extraire les atomes
    atoms = {}  # (residue_index, atom_name) -> position
    residue_types = {}  # residue_index -> code1
    residue_indices = set()

    for line in lines:
        if line.startswith('ATOM') or line.startswith('HETATM'):
            atom_name = line[12:16].strip()
            res_name = line[17:20].strip()
            res_idx = int(line[22:26].strip())
            x = float(line[30:38])
            y = float(line[38:46])
            z = float(line[46:54])

            if res_idx not in residue_types:
                residue_types[res_idx] = AA3TO1.get(res_name, 'X')
            residue_indices.add(res_idx)

            atoms[(res_idx, atom_name)] = np.array([x, y, z])

    if not residue_indices:
        raise ValueError("Aucun atome trouvé dans le fichier PDB")

    # Ordonner les résidus
    sorted_indices = sorted(residue_indices)

    # Construire la séquence
    sequence = ''.join(residue_types.get(i, 'X') for i in sorted_indices)

    # Construire la structure
    residues = []
    for i, res_idx in enumerate(sorted_indices):
        aa = get_amino_acid(residue_types.get(res_idx, 'X'))
        if aa is None:
            aa = get_amino_acid('G')  # fallback

        N = atoms.get((res_idx, 'N'), np.zeros(3))
        CA = atoms.get((res_idx, 'CA'), np.zeros(3))
        C = atoms.get((res_idx, 'C'), np.zeros(3))
        O = atoms.get((res_idx, 'O'), np.zeros(3))

        # Extraire les atomes de chaîne latérale
        sidechain = {}
        for (r_idx, name), pos in atoms.items():
            if r_idx == res_idx and name not in PDB_BACKBONE_ATOMS:
                sidechain[name] = pos

        res = ResidueAtoms(index=i, aa=aa, N=N, CA=CA, C=C, O=O,
                          sidechain=sidechain)
        residues.append(res)

    structure = ProteinStructure(sequence=sequence, residues=residues)

    # Calculer φ et ψ
    from .peptide_geometry import dihedral_angle
    for i in range(1, len(residues)):
        residues[i].phi = math.degrees(dihedral_angle(
            residues[i-1].C, residues[i].N, residues[i].CA, residues[i].C))
    for i in range(len(residues) - 1):
        residues[i].psi = math.degrees(dihedral_angle(
            residues[i].N, residues[i].CA, residues[i].C, residues[i+1].N))

    return structure


def parse_fasta(filepath: str) -> str:
    """Parse un fichier FASTA et retourne la séquence."""
    with open(filepath, 'r') as f:
        lines = f.readlines()

    sequence = ''
    for line in lines:
        line = line.strip()
        if not line.startswith('>'):
            sequence += line

    return sequence.upper()


# ═══════════════════════════════════════════════════════════════════════════════
# PDB WRITER
# ═══════════════════════════════════════════════════════════════════════════════

def write_pdb(structure: ProteinStructure, filepath: str,
              title: str = "ALPHAFOLD Harmonic Deterministic Model"):
    """
    Écrit une structure au format PDB.

    Args:
        structure: ProteinStructure à écrire
        filepath: chemin du fichier de sortie
        title: titre pour l'en-tête
    """
    lines = []
    lines.append(f"HEADER    {title}")
    lines.append(f"REMARK    Generated by ALPHAFOLD Harmonic Engine")
    lines.append(f"REMARK    Method: Deterministic ABC Fractional Dynamics")
    lines.append(f"REMARK    Sequence: {structure.sequence}")

    atom_serial = 1
    for res in structure.residues:
        res_name = AA1TO3.get(res.aa.code1, 'UNK')
        res_idx = res.index + 1

        # Backbone atoms in standard order
        for atom_name in ['N', 'CA', 'C', 'O']:
            pos = getattr(res, atom_name)
            if np.all(pos == 0):
                continue
            line = _format_atom(atom_serial, atom_name, res_name, res_idx,
                               pos[0], pos[1], pos[2])
            lines.append(line)
            atom_serial += 1

        # Sidechain atoms
        for atom_name, pos in sorted(res.sidechain.items()):
            if np.all(pos == 0):
                continue
            line = _format_atom(atom_serial, atom_name, res_name, res_idx,
                               pos[0], pos[1], pos[2])
            lines.append(line)
            atom_serial += 1

    lines.append("END\n")

    with open(filepath, 'w') as f:
        f.write('\n'.join(lines))


def _format_atom(serial: int, name: str, res_name: str, res_idx: int,
                 x: float, y: float, z: float,
                 occupancy: float = 1.0, temp_factor: float = 0.0,
                 element: str = '') -> str:
    """Formate une ligne ATOM PDB."""
    if not element:
        element = name[0] if name[0] in 'CNOS' else 'C'

    return (f"ATOM  {serial:5d} {name:<4s} {res_name:3s} A{res_idx:4d}    "
            f"{x:8.3f}{y:8.3f}{z:8.3f}"
            f"{occupancy:6.2f}{temp_factor:6.2f}          "
            f"{element:>2s}")


# ═══════════════════════════════════════════════════════════════════════════════
# MÉTRIQUES DE COMPARAISON STRUCTURALE
# ═══════════════════════════════════════════════════════════════════════════════

def compute_tm_score(mobile: np.ndarray, target: np.ndarray) -> float:
    """
    Calcule le TM-score entre deux ensembles de points Cα.

    TM-score = max [1/L_target * Σ_i 1/(1 + (d_i/d_0(L))²)]
    où d_0(L) = 1.24 * ∛(L - 15) - 1.8

    Args:
        mobile: coordonnées Cα mobiles (N×3)
        target: coordonnées Cα cibles (N×3)

    Returns:
        TM-score (0-1, plus c'est proche de 1, meilleur c'est)
    """
    from .backbone import superimpose

    L = len(target)
    if L < 12:
        return 0.0

    # Facteur d'échelle
    d0 = 1.24 * (L - 15) ** (1.0 / 3.0) - 1.8
    d0 = max(d0, 0.5)

    # Superposer
    mobile_aligned = superimpose(mobile, target)

    # Calculer le TM-score
    d = np.sqrt(np.sum((mobile_aligned - target) ** 2, axis=1))
    tm = np.mean(1.0 / (1.0 + (d / d0) ** 2))

    return float(tm)


def compute_gdt_ts(mobile: np.ndarray, target: np.ndarray) -> float:
    """
    Calcule le GDT-TS (Global Distance Test — Total Score).

    GDT-TS = moyenne des fractions de résidus sous 1, 2, 4, 8 Å
    après superposition optimale.

    Args:
        mobile: coordonnées Cα mobiles (N×3)
        target: coordonnées Cα cibles (N×3)

    Returns:
        GDT-TS score (0-1)
    """
    from .backbone import superimpose

    mobile_aligned = superimpose(mobile, target)
    d = np.sqrt(np.sum((mobile_aligned - target) ** 2, axis=1))

    thresholds = [1.0, 2.0, 4.0, 8.0]
    fractions = [np.mean(d <= t) for t in thresholds]
    gdt = np.mean(fractions)

    return float(gdt)


def compare_structures(predicted: ProteinStructure,
                       reference: ProteinStructure) -> Dict:
    """
    Compare deux structures protéiques et retourne les métriques.

    Args:
        predicted: structure prédite
        reference: structure de référence (expérimentale)

    Returns:
        Dictionnaire avec RMSD, TM-score, GDT-TS
    """
    ca_pred = predicted.ca_trace
    ca_ref = reference.ca_trace

    if len(ca_pred) != len(ca_ref):
        # Aligner sur les résidus communs
        min_len = min(len(ca_pred), len(ca_ref))
        ca_pred = ca_pred[:min_len]
        ca_ref = ca_ref[:min_len]

    rmsd_val = rmsd(ca_pred, ca_ref)
    tm = compute_tm_score(ca_pred, ca_ref)
    gdt = compute_gdt_ts(ca_pred, ca_ref)

    return {
        'rmsd_angstrom': round(rmsd_val, 3),
        'tm_score': round(tm, 4),
        'gdt_ts': round(gdt, 4),
        'n_residues_compared': len(ca_pred),
    }


# ═══════════════════════════════════════════════════════════════════════════════
# TESTS
# ═══════════════════════════════════════════════════════════════════════════════

def _test():
    """Test rapide."""
    print("=" * 60)
    print("TEST : PDB I/O et Métriques")
    print("=" * 60)

    # Créer une structure test
    bb = HarmonicBackbone("AGVL")
    struct = bb.build_extended()

    # Écrire PDB
    import tempfile, os
    with tempfile.NamedTemporaryFile(suffix='.pdb', delete=False, mode='w') as f:
        f.write("DUMMY\n")
        tmp_path = f.name
    write_pdb(struct, tmp_path)
    print(f"\nPDB écrit: {tmp_path}")

    # Relire
    struct2 = parse_pdb(tmp_path)
    print(f"Séquence lue: {struct2.sequence}")
    print(f"Résidus: {struct2.n_residues}")

    # RMSD
    from .backbone import rmsd as rmsd_fn
    r = rmsd_fn(struct2.ca_trace, struct.ca_trace)
    print(f"RMSD écriture/relecture: {r:.6f} Å")

    # TM-score
    tm = compute_tm_score(struct2.ca_trace, struct.ca_trace)
    print(f"TM-score self: {tm:.4f}")

    # GDT-TS
    gdt = compute_gdt_ts(struct2.ca_trace, struct.ca_trace)
    print(f"GDT-TS self: {gdt:.4f}")

    # Nettoyer
    os.unlink(tmp_path)

    print("\n✅ Tests passés !")


if __name__ == '__main__':
    _test()
