services:
  - type: web
    name: animation-equation-maitresse
    env: static
    staticPublishPath: engine/render_deploy
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
