branch-defaults:
  master:
    environment: hcv-pro-backend-env
    group_suffix: null

environment-defaults:
  hcv-pro-backend-env:
    branch: null
    repository: null

global:
  application_name: hcv-pro-backend
  default_platform: Python 3.11 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application

deploy:
  artifact: null
  versions:
    source_control: true
