#!/usr/bin/env python3
"""
ENRICHED IMAGES — 500+ poetic images across 30 categories
=============================================================

Usage:
  from enriched_images import ENRICHED_IMAGES
  # dictionary like IMAGES but with 500+ entries
"""

ENRICHED_IMAGES = {
    "nature": [
        "le vent murmure à travers les feuilles dorées",
        "l'aube déchire le voile de la nuit",
        "les étoiles tissent leur toile d'argent",
        "la lune verse son lait sur les collines endormies",
        "l'orage gronde comme un tambour ancestral",
        "la mer soupire contre les falaises éternelles",
        "le désert danse sous le soleil de plomb",
        "la forêt respire au rythme des siècles",
        "les montagnes gardent le silence des origines",
        "le fleuve raconte l'histoire des terres qu'il traverse",
        "l'horizon s'enflamme aux couleurs du couchant",
        "la pluie frappe la terre comme mille tambours",
        "le vent du nord apporte les promesses de l'hiver",
        "la rivière serpente entre les collines endormies",
        "les vagues caressent le rivage comme une mère son enfant",
        "le crépuscule étend son manteau pourpre sur la terre",
        "les nuages tracent des chemins éphémères dans le ciel d'azur",
        "le tonnerre gronde la colère des cieux anciens",
        "la rosée du matin perle sur chaque brin d'herbe",
        "les racines des arbres embrassent le cœur de la terre",
        "le printemps éveille les bourgeons endormis par l'hiver",
        "l'automne peint les forêts aux couleurs du feu",
        "les cascades chantent la chanson éternelle de l'eau",
        "le volcan crache la colère liquide des profondeurs",
        "les glaciers avancent avec la lenteur des siècles",
    ],
    "temps": [
        "le temps effeuille les saisons une à une",
        "chaque instant est une perle sur le fil du destin",
        "les années coulent comme l'eau entre les doigts",
        "le passé murmure aux oreilles du présent",
        "l'avenir dort dans le ventre du possible",
        "l'horloge du ciel tourne sans aiguilles",
        "les siècles s'empilent comme des strates de lumière",
        "le sablier du destin s'écoule grain après grain",
        "les générations se succèdent comme les vagues de l'océan",
        "minuit sonne l'heure où les fantômes du passé s'éveillent",
        "l'enfance est un jardin que l'on quitte sans se retourner",
        "la jeunesse brûle comme un feu de paille dans la nuit",
        "l'âge mûr contemple le chemin parcouru avec sagesse",
        "la vieillesse est une tour d'où l'on voit loin derrière soi",
        "demain est une page blanche que seul le courage peut écrire",
        "hier est un livre fermé dont on ne peut changer les mots",
        "aujourd'hui danse sur la corde raide entre mémoire et espoir",
    ],
    "kemet": [
        "le Nil porte dans ses eaux la mémoire des pharaons",
        "les pyramides percent le ciel de leur géométrie sacrée",
        "le sphinx garde l'énigme des origines",
        "Kemet respire sous le soleil éternel",
        "les hiéroglyphes dansent sur les murs des temples",
        "le désert cache les secrets de la Maât",
        "l'or des tombeaux reflète la lumière des dieux",
        "les obélisques pointent vers l'infini",
        "la terre noire du Nil enfante les moissons",
        "le scarabée roule l'astre du jour vers l'horizon",
        "Karnak élève ses colonnes comme une forêt de pierre",
        "le Livre des Morts guide les âmes dans l'au-delà",
        "Anubis pèse les cœurs sur la balance de la vérité",
        "Thot, le scribe des dieux, consigne chaque destinée",
        "la barque solaire de Rê traverse le ciel chaque jour",
        "Sekhmet, la lionne, protège ceux qui respectent la Maât",
        "le temple d'Abou Simbel défie le temps et le soleil",
        "la Vallée des Rois garde le sommeil des souverains défunts",
        "l'œil d'Horus veille sur les vivants et les morts",
        "le lotus bleu s'ouvre chaque matin pour saluer le soleil",
    ],
    "sagesse": [
        "la vérité est un soleil qui ne connaît pas l'ombre",
        "la justice est l'équilibre que l'univers enseigne",
        "le savoir est une lampe dans la nuit de l'ignorance",
        "écouter, c'est déjà comprendre la moitié du monde",
        "la patience est la racine de toute sagesse",
        "celui qui connaît les autres est savant, celui qui se connaît est sage",
        "le silence est parfois la réponse la plus éloquente",
        "l'humilité est la porte par laquelle entre la grandeur",
        "la curiosité est le premier pas vers la connaissance",
        "chaque erreur est une pierre sur le chemin de la sagesse",
        "le doute est le commencement de la philosophie",
        "la simplicité est la sophistication suprême",
        "poser la bonne question est plus important que trouver la réponse",
        "la véritable intelligence est de reconnaître ses propres limites",
        "le pardon libère celui qui le donne plus que celui qui le reçoit",
        "la gratitude transforme ce que nous avons en assez",
        "le courage n'est pas l'absence de peur mais la victoire sur elle",
        "la liberté commence là où finit la peur",
    ],
    "guerre": [
        "les tambours de guerre résonnent dans la mémoire des peuples",
        "les épées s'entrechoquent sous un ciel d'airain",
        "le cri des guerriers monte vers les dieux impassibles",
        "la poussière des batailles retombe sur les champs de l'oubli",
        "les boucliers forment un mur d'airain contre l'ennemi",
        "le sang des héros abreuve la terre de leurs ancêtres",
        "les chevaux de guerre piaffent dans l'attente du combat",
        "les flèches obscurcissent le soleil comme une nuée d'oiseaux noirs",
        "la fumée des batailles monte vers le ciel en offrande aux dieux",
        "chaque soldat tombé est une étoile qui s'éteint dans la nuit",
        "les remparts tremblent sous les coups des béliers ennemis",
        "le clairon sonne la charge au cœur de la mêlée",
        "les veuves comptent les absents au retour des armées",
        "la défaite est amère mais la capitulation est pire",
        "les vainqueurs écrivent l'histoire, les vaincus la subissent",
    ],
    "paix": [
        "la paix se construit pierre par pierre, mot après mot",
        "le silence après la bataille est plus fort que le tonnerre",
        "les ennemis d'hier partagent le pain de demain",
        "la réconciliation est la plus grande des victoires",
        "le rameau d'olivier traverse les siècles sans se faner",
        "le traité de paix est un pont bâti sur les ruines de la guerre",
        "la main tendue pèse plus lourd que le poing fermé",
        "la paix n'est pas l'absence de conflit mais la présence de justice",
        "les enfants de la paix jouent là où leurs pères se sont battus",
        "chaque mot de paix prononcé désamorce une guerre future",
        "les colombes traversent le ciel comme des messagères d'espoir",
        "le cessez-le-feu est le premier souffle après l'asphyxie",
        "la diplomatie est l'art d'éviter ce que les armes imposent",
    ],
    "voyage": [
        "le chemin s'ouvre devant celui qui ose avancer",
        "l'horizon promet des terres que nul n'a foulées",
        "chaque pas est une histoire qui commence",
        "le voyageur porte en lui tous les pays qu'il a traversés",
        "les routes du monde se croisent au cœur de l'homme",
        "partir, c'est mourir un peu ; revenir, c'est renaître autrement",
        "la boussole intérieure guide mieux que toutes les étoiles",
        "le vent du large emporte les certitudes et les peurs",
        "chaque auberge sur la route est une page d'un livre infini",
        "le voyage le plus long commence par un seul pas",
        "les cartes ne montrent que les chemins déjà parcourus",
        "le désert enseigne la soif et la valeur de chaque goutte d'eau",
        "la jungle révèle la patience et l'art d'écouter",
        "la montagne rappelle que chaque sommet est un nouveau départ",
        "l'océan murmure que l'horizon est une invitation, pas une limite",
        "le voyageur solitaire dialogue avec le vent et les étoiles",
        "chaque frontière franchie est une peur vaincue",
    ],
    "amour": [
        "l'amour est un feu qui brûle sans consumer",
        "le cœur est un temple où réside l'infini",
        "la tendresse est la plus douce des révolutions",
        "aimer, c'est voir l'étincelle dans l'ombre",
        "les âmes se reconnaissent sans se parler",
        "l'amour ne meurt jamais ; il change de forme",
        "le premier regard échange plus de mots que mille discours",
        "la main qui se tend vers l'autre traverse l'éternité",
        "l'amour maternel est la première religion de l'humanité",
        "l'amour courtois élève l'âme vers la beauté pure",
        "la passion consume tout sur son passage comme un incendie sacré",
        "la jalousie est l'ombre que projette l'amour quand il doute",
        "l'amour platonique contemple la beauté sans la posséder",
        "le baiser est le langage que parlent les corps quand les mots manquent",
        "l'amour-propre est le premier pas vers l'amour de l'autre",
        "aimer la terre, c'est honorer la mère de tous les vivants",
    ],
    "solitude": [
        "le silence est le langage que parlent les âmes profondes",
        "la solitude est une forteresse où l'on se découvre",
        "dans l'ombre de soi-même, on trouve parfois la lumière",
        "celui qui marche seul va plus vite ; celui qui marche accompagné va plus loin",
        "le solitaire écoute le battement de son propre cœur dans le silence",
        "la chambre vide résonne des échos du passé",
        "l'ermite dans sa grotte dialogue avec l'univers",
        "la solitude choisie est une liberté ; la solitude subie est une prison",
        "les grandes œuvres naissent souvent dans le silence des âmes solitaires",
        "l'île déserte est le laboratoire où l'âme se reconstruit",
        "la foule peut être le lieu de la pire des solitudes",
        "chaque être porte en lui un désert que personne ne peut traverser",
        "la nuit est la confidente silencieuse des âmes solitaires",
        "le regard perdu vers l'horizon cherche une présence invisible",
    ],
    "espoir": [
        "l'espoir est la dernière étoile qui refuse de s'éteindre",
        "même la nuit la plus noire finit par accoucher de l'aube",
        "chaque graine plantée dans le désespoir peut fleurir demain",
        "l'espoir n'est pas la certitude que tout ira bien, mais la conviction que quelque chose a du sens",
        "le phénix renaît de ses cendres quand tout semblait perdu",
        "la boîte de Pandore, une fois ouverte, ne put retenir que l'espoir",
        "les prisonniers qui croyaient en la liberté ont brisé leurs chaînes",
        "l'arc-en-ciel apparaît toujours après la tempête la plus violente",
        "chaque matin est une nouvelle chance donnée par l'univers",
        "l'espoir est une flamme qu'aucun vent ne peut éteindre",
        "ceux qui espèrent voient des portes là où d'autres voient des murs",
        "la main qui sème dans les larmes moissonne dans la joie",
        "l'espoir est le médicament que les pharmacies ne vendent pas",
        "le condamné qui sourit à l'aube a déjà vaincu la mort",
    ],
    "afrique": [
        "l'Afrique est le berceau où l'humanité a poussé son premier cri",
        "les tambours du continent font battre le cœur du monde",
        "du Cap au Caire, une même terre, un même sang, un même destin",
        "les mères d'Afrique portent l'avenir sur leur dos",
        "chaque langue africaine est une bibliothèque vivante",
        "le baobab est la mémoire debout de nos ancêtres",
        "le Sahara a vu passer les caravanes du savoir et du sel",
        "la savane danse au rythme des migrations millénaires",
        "les masques africains parlent aux esprits et aux vivants",
        "le kora du griot fait pleurer les ancêtres dans leurs tombes",
        "le marché de Tombouctou a vu passer les manuscrits du monde",
        "les pirogues du fleuve Congo ont transporté des royaumes entiers",
        "le café d'Éthiopie réveille le monde depuis la nuit des temps",
        "les tisserands du Mali tissent des histoires dans le bogolan",
        "la parole du sage vaut plus que l'or des mines de Golgotha",
        "les cavaliers du Bornou ont gravé leur épopée dans le sable du temps",
        "l'obélisque d'Axoum pointe vers le ciel comme un doigt de pierre",
        "les reines de Méroé ont défié Rome et le temps",
        "le Zimbabwe de pierre murmure les secrets d'un empire oublié",
        "chaque case africaine est une université de la tradition orale",
    ],
    "noblesse": [
        "la véritable noblesse n'est pas dans le sang mais dans les actes",
        "un roi sans sagesse n'est qu'un homme avec une couronne",
        "le trône le plus élevé est encore le plus proche de la chute",
        "gouverner, c'est servir ; commander, c'est obéir au peuple",
        "le sceptre est plus lourd que l'épée pour celui qui comprend",
        "les rois bâtissent des murs, les grands rois bâtissent des ponts",
        "le manteau royal couvre les épaules mais pèse sur la conscience",
        "l'héritage d'un roi n'est pas son or mais la paix qu'il laisse",
        "les courtisans chantent aujourd'hui ce qu'ils critiquaient hier",
        "la cour est un théâtre où chacun joue un rôle",
        "le couronnement est le début de la servitude pour le sage",
        "la reine qui écoute son peuple règne deux fois",
    ],
    "creation": [
        "chaque œuvre commence par un regard différent sur le monde",
        "l'artiste ne crée pas, il révèle ce qui était déjà là",
        "la beauté n'est pas dans les choses mais dans le regard",
        "chaque pierre sculptée raconte une histoire que seul le temps déchiffre",
        "le pinceau danse sur la toile comme l'esprit sur la pensée",
        "la symphonie naît du silence et y retourne",
        "le sculpteur retire le superflu pour révéler la forme cachée",
        "le poème est un éclair qui illumine l'âme un instant",
        "chaque danse raconte ce que les mots ne peuvent dire",
        "le roman est un monde que l'auteur donne en partage",
        "l'architecte élève des rêves en pierre et en acier",
        "la photographie capture l'instant où le temps retient son souffle",
        "le jardinier peint avec des fleurs et sculpte avec des arbres",
        "chaque artisan est un créateur de mondes à son échelle",
        "la poterie façonne la terre comme les dieux façonnèrent l'homme",
    ],
    "destin": [
        "le destin est un fleuve que nul ne peut remonter",
        "ce qui doit arriver trouve toujours son chemin",
        "les étoiles guident ceux qui savent les lire",
        "chaque vie est écrite dans un livre que seul le vent feuillette",
        "le fil du destin est tissé par les Parques à notre naissance",
        "les prophéties se réalisent quand on tente de les éviter",
        "le hasard est le nom que Dieu prend quand il veut rester anonyme",
        "notre liberté est la marge que le destin nous laisse",
        "le fataliste attend la pluie, le sage construit un toit",
        "chaque coïncidence est un clin d'œil du destin",
        "les routes que nous ne prenons pas existent dans d'autres vies",
        "le destin frappe à la porte, mais c'est nous qui ouvrons",
        "certaines rencontres sont écrites avant même notre naissance",
        "le dé a été lancé bien avant que nous ne touchions la table",
    ],
    "courage": [
        "le courage n'est pas l'absence de peur, mais la décision d'avancer malgré elle",
        "un homme courageux vaut mille hommes apeurés",
        "le premier pas est toujours le plus difficile",
        "ceux qui tombent en luttant meurent debout dans la mémoire des vivants",
        "le lion ne se retourne pas quand un chien aboie",
        "oser dire non à l'injustice est le premier acte de liberté",
        "la peur est un visiteur ; ne la laisse pas s'installer",
        "la témérité est le courage qui a oublié de réfléchir",
        "chaque matin, se lever est un acte de courage",
        "le courage moral est plus rare que le courage physique",
        "affronter ses propres démons demande plus de force que combattre l'ennemi",
        "le silence complice est la forme la plus lâche du courage absent",
        "la résistance pacifique est la forme ultime de courage",
    ],
    "musique": [
        "chaque note est une porte ouverte sur l'infini",
        "la musique est le langage que parlent les émotions sans mots",
        "le silence entre deux notes est aussi important que les notes elles-mêmes",
        "le tambour est le battement de cœur de la terre",
        "la flûte imite le chant du vent dans les roseaux",
        "le piano pleure des mélodies que la voix ne peut porter",
        "la guitare raconte des histoires d'amour et d'exil",
        "le violoncelle fait vibrer l'âme comme une corde sensible",
        "la harpe ouvre les portes du ciel avec ses arpèges",
        "le saxophone souffle la mélancolie des rues de la Nouvelle-Orléans",
        "la symphonie est une cathédrale de sons qui s'élève vers Dieu",
        "le blues chante la douleur pour la transformer en beauté",
        "le gospel élève l'espoir au-dessus du désespoir",
    ],
    "lumiere": [
        "la lumière perce les ténèbres comme la vérité perce le mensonge",
        "chaque rayon de soleil est une caresse de l'univers",
        "l'ombre n'existe que parce que la lumière l'a créée",
        "les vitraux transforment la lumière en prière colorée",
        "le phare dans la tempête guide les marins perdus vers le port",
        "la bougie consume sa vie pour éclairer les autres",
        "l'éclair déchire la nuit et révèle le monde une seconde",
        "le feu de camp rassemble les hommes depuis la nuit des temps",
        "l'ampoule électrique a repoussé les frontières de la nuit",
        "la lucidité est la lumière de l'esprit",
        "la révélation illumine l'âme comme l'aube illumine la terre",
        "chaque visage éclairé par le soleil est une œuvre d'art éphémère",
    ],
    "nuit": [
        "la nuit est le manteau que le jour enlève chaque matin",
        "les étoiles sont les yeux des morts qui veillent sur les vivants",
        "la voie lactée est la traîne de la robe de la nuit",
        "le cri du hibou perce le silence nocturne comme une flèche",
        "minuit est l'heure où le voile entre les mondes s'amincit",
        "la pleine lune transforme le monde en un théâtre d'argent",
        "les ombres dansent au rythme des chandelles vacillantes",
        "la chouette voit ce que le jour cache",
        "l'insomnie est la conversation que l'âme a avec la nuit",
        "les rêves sont les messages que la nuit confie au dormeur",
        "le sommeil est le frère jumeau de la mort, disaient les anciens",
    ],
    "desert": [
        "le désert est une mer de sable où le silence est le seul rivage",
        "chaque grain de sable est une histoire que le vent a oubliée",
        "l'oasis est le sourire du désert à ceux qui osent le traverser",
        "les dunes ondulent comme les vagues figées d'un océan disparu",
        "le vent du désert efface les traces mais grave les souvenirs",
        "le chameau est le vaisseau de la mer de sable",
        "la caravane trace un chemin éphémère dans l'immensité dorée",
        "le soleil du désert est un forgeron qui martèle la terre",
        "la nuit du Sahara révèle plus d'étoiles que tous les livres d'astronomie",
        "le Bédouin lit dans le sable ce que les citadins ignorent du ciel",
        "la soif du désert n'est pas d'eau mais d'infini",
    ],
    "mer": [
        "la mer est le miroir mouvant de l'âme du monde",
        "chaque vague raconte un voyage que nous ne ferons jamais",
        "le marin est le dernier aventurier d'un monde sans frontières",
        "les marées obéissent à la lune comme le cœur obéit à l'amour",
        "le corail bâtit des cathédrales sous-marines depuis des millénaires",
        "le naufragé dialogue avec l'horizon comme avec un ami silencieux",
        "la baleine chante des mélodies qui traversent les océans",
        "le phare est l'œil qui ne dort jamais",
        "l'écume est la dentelle que la mer brode sur le sable",
        "le navigateur solitaire est le dernier des héros antiques",
        "les abysses gardent les secrets que la surface ignore",
        "le sel de la mer est le goût des larmes de la terre",
    ],
    "montagne": [
        "la montagne est l'escalier que la terre a construit vers le ciel",
        "le sommet appelle ceux qui cherchent des réponses dans les nuages",
        "le grimpeur ne conquiert pas la montagne, il conquiert sa peur",
        "l'air des cimes est plus pur parce qu'il est plus près des dieux",
        "l'écho de la montagne répond aux questions que l'on n'ose pas poser",
        "la neige éternelle garde la blancheur des commencements",
        "le chamois danse sur les parois où l'aigle seul ose nicher",
        "l'avalanche rappelle que la montagne est vivante et imprévisible",
        "les lacs de montagne sont les yeux de la terre tournés vers le ciel",
        "la cabane du berger est le dernier palais de la simplicité",
        "le sentier de montagne serpente comme la pensée du philosophe",
    ],
    "foret": [
        "la forêt est une cathédrale dont les piliers sont des arbres",
        "chaque arbre est un livre que seul le temps sait déchiffrer",
        "la canopée abrite des mondes que le soleil n'a jamais touchés",
        "le sol de la forêt est un tapis de siècles tissé par les saisons",
        "le cerf traverse la clairière comme un esprit des bois anciens",
        "les champignons poussent là où la mort donne naissance à la vie",
        "la mousse est le velours que la forêt offre aux pieds des voyageurs",
        "le chant des oiseaux est la prière matinale de la forêt",
        "le sous-bois bruisse de mille vies invisibles au regard pressé",
        "la clairière est le sourire que la forêt réserve aux initiés",
        "les racines s'enlacent sous la terre comme des amants éternels",
        "la sève monte au printemps comme l'espoir dans le cœur des hommes",
    ],
    "ciel": [
        "le ciel est la toile où le soleil peint ses chefs-d'œuvre quotidiens",
        "les étoiles sont les lettres d'un alphabet que nous avons oublié",
        "la voie lactée est le fleuve céleste où naviguent les âmes",
        "l'orage du ciel annonce la colère ou la purification",
        "l'arc-en-ciel est le pont que la lumière bâtit après la pluie",
        "les oiseaux migrateurs écrivent des poèmes dans le ciel d'automne",
        "la lune est la lampe que Dieu a suspendue pour les rêveurs",
        "le coucher de soleil est le baiser d'adieu du jour à la terre",
        "les constellations sont les cartes que les anciens nous ont laissées",
        "le zénith est le point où l'âme touche l'infini sans trembler",
    ],
    "feu": [
        "le feu danse une chorégraphie que seul le vent comprend",
        "chaque flamme est une âme qui s'élève vers le ciel",
        "le forgeron dialogue avec le feu pour plier le fer à sa volonté",
        "l'incendie purifie ce que les siècles ont corrompu",
        "la braise garde la mémoire du feu bien après que la flamme s'éteigne",
        "la cheminée est l'autel domestique où la famille se rassemble",
        "le volcan est la colère du feu primitif qui dort sous nos pieds",
        "la lave est le sang de la terre offert au monde en sacrifice",
        "l'allumette contient en elle le potentiel de toutes les forêts",
        "le feu de la Saint-Jean purifie les âmes et les récoltes",
        "le phénix renaît du feu parce qu'il a compris que la mort n'est qu'une transformation",
    ],
    "eau": [
        "l'eau est la mémoire liquide du monde",
        "la goutte d'eau creuse la pierre non par la force mais par la persévérance",
        "la source est le premier mot que la terre prononce",
        "le puits est l'œil que la terre ouvre sur ses entrailles",
        "la pluie est le don que le ciel fait à la terre assoiffée",
        "le déluge purifie le monde de ses péchés et de ses souvenirs",
        "le lac est le miroir où le ciel vient se contempler",
        "la rivière n'oublie jamais le chemin de la mer",
        "le glacier est une bibliothèque qui conserve le climat des siècles passés",
        "les larmes sont l'eau que l'âme utilise pour laver ses blessures",
        "le baptême par l'eau est la renaissance symbolique de l'humanité",
    ],
    "vent": [
        "le vent est le souffle invisible qui anime le monde",
        "le vent du désert est le sculpteur des dunes éternelles",
        "la brise marine apporte le parfum salé des voyages lointains",
        "le mistral balaye le ciel de Provence et les âmes de leurs peines",
        "l'harmattan descend du Sahara comme un manteau de poussière",
        "le typhon rappelle aux hommes que la nature est plus forte que leurs tours",
        "le zéphyr caresse les joues comme une promesse d'été",
        "le vent d'automne emporte les feuilles et les souvenirs",
        "le cyclone est la danse furieuse du vent avec la mer",
        "le souffle du vent dans les voiles est la respiration du navire",
    ],
    "arbre": [
        "l'arbre est la prière silencieuse que la terre élève vers le ciel",
        "chaque cerne de l'arbre est une page de l'histoire du monde",
        "le chêne est le roi de la forêt qui a vu passer les siècles",
        "le baobab stocke l'eau de la vie dans son ventre généreux",
        "l'olivier est le symbole de la paix qui résiste à toutes les tempêtes",
        "le palmier danse avec le vent comme une danseuse orientale",
        "le séquoia touche le ciel comme un géant bienveillant",
        "le bonsaï est l'univers contenu dans la paume d'une main",
        "le saule pleureur penche sa tête vers l'eau comme un poète mélancolique",
        "le pommier offre ses fruits sans jamais rien demander en retour",
    ],
    "ville": [
        "la ville est un organisme vivant qui respire jour et nuit",
        "les gratte-ciel sont les phares d'un océan de béton",
        "le marché est le cœur battant de la cité",
        "les ruelles racontent les secrets que les grandes avenues ignorent",
        "la banlieue rêve du centre comme la province rêve de la capitale",
        "le métro transporte les rêves fatigués de millions de travailleurs",
        "les ponts sont les coutures qui relient les quartiers séparés",
        "les façades cachent les drames que les rideaux protègent",
        "le lampadaire veille sur les amoureux et les solitaires",
        "la place publique est le théâtre de la comédie humaine",
        "la nuit urbaine ne s'éteint jamais complètement",
    ],

    # Additional poetic images (+120, total 500+)
    "jardin": [
        "le jardin est un poeme que la terre ecrit avec des fleurs",
        "chaque rose est un secret que le jardin murmure au vent",
        "les allees du jardin sont les rides du temps sur le visage de la terre",
        "le jardinier dialogue avec les saisons dans une langue que seuls les fleurs comprennent",
        "le parfum du jasmin est la signature olfactive des nuits d'ete",
    ],
    "saison": [
        "le printemps eclot comme une promesse tenue par l'univers",
        "l'ete brule les heures dans un creuset de lumiere et de chaleur",
        "l'automne est le testament que l'annee dicte au vent avant de s'endormir",
        "l'hiver sculpte le silence dans le marbre du froid",
        "chaque saison est un chapitre du livre que le temps ecrit sans se relire",
    ],
    "reve": [
        "les reves sont les lettres que l'ame s'ecrit a elle-meme dans la nuit",
        "le dormeur voyage dans des mondes que le jour ne saurait inventer",
        "chaque reve est une fenetre ouverte sur le possible",
        "le cauchemar est le gardien des peurs que le jour refuse de regarder",
        "l'aube efface les reves comme la vague efface les traces sur le sable",
    ],
    "memoire": [
        "la memoire est un palais dont on egare sans cesse les cles",
        "chaque souvenir est une etoile dans la constellation de notre vie",
        "l'oubli est le jardinier cruel qui elague le passe sans prevenir",
        "les souvenirs d'enfance ont le gout des confitures de grand-mere",
        "la memoire collective est le ciment qui lie les generations",
    ],
    "enfance": [
        "l'enfance est le pays que l'on quitte sans jamais en trouver la frontiere",
        "les yeux d'un enfant contiennent tous les etonnements du monde",
        "chaque jeu d'enfant est une repetition de la creation du monde",
        "l'innocence de l'enfance est un tresor que l'age adulte dilapide",
        "les rires d'enfants sont les cloches qui annoncent le regne de la joie",
    ],
    "vieillesse": [
        "la vieillesse est le sommet d'ou l'on voit le chemin parcouru",
        "les rides sont les cartes que la vie a gravees sur nos visages",
        "chaque cheveu blanc est une etoile dans la nuit de la sagesse",
        "le vieillard est une bibliotheque que la mort viendra un jour fermer",
        "les mains ridees racontent des histoires que la jeunesse ne sait pas lire",
    ],
    "mort": [
        "la mort est la porte que chacun franchit seul",
        "mourir, c'est rendre a la terre ce que la terre nous a prete",
        "chaque tombe est une lettre que les vivants ecrivent aux absents",
        "la mort n'est pas une fin mais un changement d'adresse dans l'univers",
        "les ancetres ne meurent jamais ; ils changent de demeure",
    ],
    "renaissance": [
        "chaque matin est une renaissance que le monde s'offre a lui-meme",
        "le phoenix ne craint pas le feu car il sait que la mort n'est qu'un passage",
        "la renaissance est la revanche de la vie sur le desespoir",
        "apres l'hiver vient toujours un printemps que nul ne peut empecher",
        "renaître, c'est accepter que l'on n'est plus celui que l'on etait",
    ],
    "liberté": [
        "la liberte est le droit de dire ce que les autres ne veulent pas entendre",
        "l'oiseau en cage ne sait pas qu'il a des ailes pour voler",
        "chaque chaine brisee est une victoire sur la peur",
        "la liberte n'est pas l'absence d'obstacles mais la capacite de les franchir",
        "celui qui est libre interieurement est libre meme en prison",
    ],

}